### ISSUE TITLE
help wanted - Naming Conventions

### ISSUE THREAD

**Issue by selvi-22** [Aksha018/E-commerce-for-Bakery-shop#1]
As per best practices, **variables** should follow **smallCamelCase** naming convention.

![image](https://user-images.githubusercontent.com/106646977/182290410-c048891a-7003-4e6c-a828-225f2f5d0946.png)

![image](https://user-images.githubusercontent.com/106646977/182290674-a0e4a88e-d161-4526-8565-81155caa6280.png)

**Comment by Aksha018** [comment]
Issues fixed
