### ISSUE TITLE
help wanted - Naming Standards

### ISSUE THREAD

**Issue by selvi-22** [Aksha018/E-commerce-for-Bakery-shop#2]
In Model, it is recommended to follow java naming conventions

![image](https://user-images.githubusercontent.com/106646977/182291998-b0740e4a-8588-4e2d-b2b8-e5abc83402bd.png)

![image](https://user-images.githubusercontent.com/106646977/182292190-2c0c5667-2704-4195-b159-f6695bcbb22c.png)

![image](https://user-images.githubusercontent.com/106646977/182292355-5afdfddd-22d5-473c-87d3-a16d8572d9dc.png)

![image](https://user-images.githubusercontent.com/106646977/182292470-0e490962-4b37-40e7-9edc-39fcb96e7261.png)

**Comment by Aksha018** [comment]
Naming convention issues fixed
